# fly.toml app configuration file generated for cutedog-app on 2023-12-25T23:26:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cutedog-app"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
